# 图像轮廓

- 什么是图像轮廓
    - 边缘检测能够检测出图像边缘，但边缘是不连续的
    - 将边缘连接为一个整体，就构成轮廓
- 注意问题：
    - 轮廓处理的图像需要是二值图像，所以需要先进行阈值分割或边缘检测处理
    - 查找轮廓需要更改原始图像，因此通常使用原始图像的拷贝进行操作
    - 在opencv中，是从黑色背景中查找白色对象，因此，对象必须是白色的，背景必须是黑色的
    
- 使用的函数
    - cv2.findContours(): 查找图像的轮廓，返回图像的轮廓信息
        - 语法：img, contours, hierarchy = cv2.findContours(image, mode, method)
            - 返回值
                - image: 是修改(进行二值化处理）后的原始图像
                - contours: 轮廓
                - hierarchy: 图像的拓扑信息（轮廓的层次）
            - 参数
                - image: 原始图像
                - mode: 轮廓的检索模式
                    - cv2.RETR_EXTERNAL: 表示只检测外轮廓
                    - cv2.RETR_LIST: 检测的轮廓不建立等级关系
                    - cv2.RETR_CCOMP: 建立两个等级的轮廓，上面一层为外边界，里面一层为内孔的边界信息。
                        - 如果孔内还有一个联通的物体，这个物体的边界也在上面一层
                    - cv2.RETR_TREE: 建立一个等级树结构的轮廓，一般是使用等级树的检索模式
                - method: 轮廓的近似方法
                    - cv2.CHAIN_APPROX_NONE: 存储所有的轮廓点，相邻的两个点的像素位置差不超过1
                        - 即max(abs(x1-x2), abs(y2-y1)) == 1
                    - cv2.CHAIN_APPROX_SIMPLE: 压缩水平方向，垂直方向和对角线方向的元素，只保留该方向的终点坐标
                        - 例如一个矩形轮廓只需4个点来保存轮廓信息
                    - cv2.CHAIN_APPROX_TC89_L1: 使用teh-chinl chain的一种近似算法
                    - cv2.CHAIN_APPROX_TC89_KCOS: 使用teh-chinl chain的一种近似算法
                    
    - cv2.drawContours()：绘制图像的轮廓，它的输入是findContours的返回值
        - 语法：r = cv2.drawContours(o, contours, contourIdx, color [, thickness])
            - 返回值：
                - r： 目标图像，直接修改目标的像素点，实现绘制
            - 参数：
                - o: 原始图像
                - contours: 需要绘制的边缘数组，是findContours函数的返回值之一
                - contoursIdx: 需要绘制的边缘索引（如果想绘制第一个轮廓则该参数为0，一次类推），如果要绘制所有轮廓则该参数为-1
                - color: 绘制的颜色，为BGR格式的标量Scalar（一般表示(b,g,r), b,g,r取值都在0-255之间）
                - thickness: 可选参数，绘制的密度，即描绘轮廓时所用的画笔粗细，以像素值为单位(=8表示画笔粗细为8像素)

In [13]:
import cv2
import numpy as np

o = cv2.imread('image/contours.bmp')

# 先将BGR图像调整为灰度图像
gray = cv2.cvtColor(o, cv2.COLOR_BGR2GRAY)

# 对灰度图像使用阈值处理的方式，转换成二值图像，返回值为binary
ret, binary = cv2.threshold(gray, 127, 255, cv2.THRESH_BINARY)
print(ret)   # 127.0

# 检索轮廓
contours, hierarchy = cv2.findContours(binary, 
                                       cv2.RETR_TREE, 
                                       cv2.CHAIN_APPROX_SIMPLE)
print(hierarchy)   # 三组轮廓边缘数组值
#  [[[ 1 -1 -1 -1]
#    [ 2  0 -1 -1]
#    [-1  1 -1 -1]]]

# 绘制轮廓
# 先复制原始图像
co = o.copy()
# 对复制后的原始图像进行绘制
r = cv2.drawContours(co, contours, -1, (0, 0, 255), 8)

# 显示图像
cv2.imshow('original', o)
# cv2.imshow('gray', gray)
# cv2.imshow('two', binary)
cv2.imshow('result', r)
cv2.waitKey()
cv2.destroyAllWindows()

127.0
[[[ 1 -1 -1 -1]
  [ 2  0 -1 -1]
  [-1  1 -1 -1]]]
