In [1]:
import cv2

## 1. 图像

### 1. 1 读入图像

- img = cv2.imread(文件名[, 显示控制参数])
    - cv.IMREAD_UNCHANGED 显示原图
    - cv.IMREAD_GRAYSCALE 显示灰度图
    - cv.IMREAD_COLOR 显示彩色图
    - 更多参数参见官网

### 1.2 显示图像

- cv2.imshow(窗口名称,图像名称)
- cv2.waitKey([, delay])
    - delay>0, 等待delay毫秒
    - delay<0, 等待键盘单击
    - delay=0, 无限等待（默认）
- cv2.destroyAllWindows(窗口名)
    - 无参数则关闭所有窗口，并从内存中删除

### 1.3 保存图像

- cv2.imwrite(保存文件的地址, 要保存的文件名) 

In [2]:
# 示例
img = cv2.imread('../image/test.png')
cv2.imshow('demo', img)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.imwrite('../image/test1.jpg', img)

True

## 2. 图像处理基础

- 图像是由像素构成的
- 图像分类
    - 二值图像：黑白（1，0），每个像素点是单个值
    - 灰度图像：把灰度（黑到白）分为256个（0-255，0纯黑，255纯白）不同的颜色，每个像素点是单个值
    - RGB图像：每个像素点是三个值
        - 一般情况是（R,G,B）
        - 在opencv里面的通道顺序是（B,G,R）
            - 所以在opencv里面，一般先根据习惯把通道顺序处理成(R,G,B)

## 3. 像素处理

### 3.1 读取像素

- 返回值= 图像名（位置参数）
    - 位置参数：行+列

### 3.2 修改像素值

- 图像名（位置参数）= 新的像素值
    - img[13, 13] = [B值, G值, R值]

In [3]:
pix = img[13, 13]
print(pix)
print(pix[0])   # blue
print(pix[1])   # green
print(pix[2])   # red

[ 79 133 116]
79
133
116


In [4]:
img[13, 13] = [215, 0, 133]
print(img[13, 13])

import matplotlib.pyplot as plt
plt.imshow(img, cmap='viridis', interpolation='bicubic')
plt.show()

[215   0 133]


<Figure size 640x480 with 1 Axes>

In [5]:
src = cv2.imread('../image/lenacolor.png')
print(src[100,100,0])
print(src[100,100,1])
print(src[100,100,2])
print(src[100,100])

78
68
178
[ 78  68 178]


In [6]:
src[100:150, 100:150] = [255, 255, 255]
cv2.imshow('demo', src)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.imwrite('../image/lena_changed_color.jpg', src)

True

## 4. 用numpy处理像素

### 4.1 读取像素

- 用img.item函数
    - 灰度图像: p = img.item(位置)
    - RGB图像：要分别读取每个通道的值
        - p = img.item(位置，通道) 

### 4.2 修改像素

- 用img.itemset函数
    - 灰度图像：img.itemset(位置，新值)
    - BGR图像：分别设置每个通道的新值
        - img.itemset((位置，通道), 新值)

In [7]:
import numpy as np
print(src.item(100,100,0), src.item(100, 100, 1), src.item(100, 100, 2))

255 255 255


## 5. 获取图像属性

### 5.1 形状属性

- img.shape
    - 灰度图像：行数、列数
    - 彩色图像：行数、列数、通道

In [8]:
print(src.shape)

img1 = cv2.imread('../image/lena256.bmp', cv2.IMREAD_UNCHANGED)
print(img1.shape)

(512, 512, 3)
(256, 256)


### 5.2 像素点数

- img.size
    - 灰度图像： 行数*列数
    - 彩色图像： 行数*列数*像素数

In [9]:
print(src.size)
print(img1.size)

786432
65536


### 5.3 图像数据类型

- img.dtype
    - 返回图像的数据类型

In [10]:
print(src.dtype)
print(img1.dtype)

uint8
uint8


## 6. 图像ROI(region of interest)

- ROI 感兴趣区域：从被处理图像以方框、圆形、椭圆、不规则多边形等方式勾勒出需要处理的区域
- 可以通过算子（operator）和函数来求得感兴趣区域ROI，并进行图像的下一步处理
- 简单的方式可以通过下标的方式
    - img[200:300, 200:400]

In [13]:
face = src[200:400, 200:360]
print(face)
cv2.imshow('face', face)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[ 90  51 127]
  [ 81  43 126]
  [ 93  54 134]
  ...
  [115  89 153]
  [126 111 161]
  [134 120 176]]

 [[ 89  42 115]
  [ 90  43 110]
  [102  54 121]
  ...
  [118  87 157]
  [111  80 154]
  [119 101 171]]

 [[ 98  55 117]
  [104  58 123]
  [103  63 118]
  ...
  [137 103 164]
  [102  74 146]
  [125  92 160]]

 ...

 [[ 53  19  90]
  [ 66  22  91]
  [ 58  22  88]
  ...
  [ 91  69 142]
  [ 73  49 131]
  [ 83  62 139]]

 [[ 62  27  99]
  [ 61  22  88]
  [ 63  18  84]
  ...
  [ 84  65 140]
  [ 74  50 132]
  [ 84  60 139]]

 [[ 63  31  95]
  [ 71  31  86]
  [ 63  22  84]
  ...
  [ 79  63 142]
  [ 78  53 132]
  [ 87  62 142]]]


In [27]:
import cv2
import numpy as np
img1 = cv2.imread('../image/lenacolor.png', cv2.IMREAD_UNCHANGED)
img2 = cv2.imread('../image/girl.bmp', cv2.IMREAD_UNCHANGED)



img1_roi = img1[220:380, 200:350]
img1[0:160, 0:150] = img1_roi
img2[0:160, 0:150] = img1_roi
cv2.imshow('original', img1)
cv2.imshow('changed', img2)
cv2.imshow('face', img1_roi)


cv2.waitKey(0)
cv2.destroyAllWindows()

## 7. 通道的拆分与合并

### 7.1 拆分cv2.split()

- 指将图像拆分成三个独立的通道
    - 拆分的结果是三个灰度图像
    - 方法1：切片
    - 方法2：cv2.split(要拆分的图像名)
        - cv2.split(要拆分的图像名)[0] 得到b通道
        - 其他通道类似


### 7.2 合并cv2.merge()

- 将独立的三个通道合并成rgb彩色图像
- 使用cv2.merge([要合并的灰度图像])

In [31]:
# b = img1[:, :, 0]
# g = img1[:, :, 1]
# r = img1[:, :, 2]

# 使用split函数
# b, g, r = cv2.split(img1)

b = cv2.split(img1)[0]
g = cv2.split(img1)[1]
r = cv2.split(img1)[2]

cv2.imshow('blue', b)
cv2.imshow('green', g)
cv2.imshow('red', r)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [32]:
# 合并
bgr = cv2.merge([b,g,r])
rgb = cv2.merge([r,g,b])
rbg = cv2.merge([r,b,g])
cv2.imshow('bgr', bgr)
cv2.imshow('rgb', rgb)
cv2.imshow('rbg', rbg)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [36]:
# 只使用一个通道的合并——蓝色
rows, cols, chns = img1.shape

b = cv2.split(img1)[0]
g = np.zeros((rows, cols), dtype=img1.dtype)
r = np.zeros((rows, cols), dtype=img1.dtype)
m = cv2.merge([b, g, r])
cv2.imshow('merged', m)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [37]:
# 只使用一个通道的合并——绿色
rows, cols, chns = img1.shape

g = cv2.split(img1)[1]
b = np.zeros((rows, cols), dtype=img1.dtype)
r = np.zeros((rows, cols), dtype=img1.dtype)
m = cv2.merge([b, g, r])
cv2.imshow('merged', m)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [41]:
# 只使用一个通道的合并——红色
rows, cols, chns = img1.shape
print(rows)
print(cols)
print(chns)

r = cv2.split(img1)[2]
print(r)
g = np.zeros((rows, cols), dtype=img1.dtype)
print(g)
b = np.zeros((rows, cols), dtype=img1.dtype)
m = cv2.merge([b, g, r])
cv2.imshow('merged', m)
cv2.waitKey(0)
cv2.destroyAllWindows()

512
512
3
[[ 87  91  93 ... 230 221 200]
 [ 92  84  93 ... 230 221 200]
 [ 92  86  83 ... 230 221 200]
 ...
 [ 84  84  92 ... 173 172 177]
 [ 82  82  96 ... 179 181 185]
 [ 83  82  96 ... 179 181 185]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


## 8.图像运算：图像加法运算

### 8.1 numpy加法：取模运算

- 取模加法: 结果 = 图像1 + 图像2
    - 如果结果的像素值<=255, 则直接取结果值
    - 如果结果的像素值>255, 则结果对255取模  255+58=(255+58)%255=58
- 注意的问题：
    - 参与运算的图像大小、类型必须一致

### 8.2 OpenCV的加法:饱和运算

- 饱和运算加法： 结果 = cv2.add(图像1，图像2)
    - 如果结果的像素值<=255, 则直接取结果值
    - 如果结果的像素值>255, 则结果取255
- 注意的问题：
    - 参与运算的图像大小、类型必须一致

In [43]:
import cv2
import numpy as np

img = cv2.imread('../image/lena512.bmp')
img1 = img
res1 = img + img1
res2 = cv2.add(img, img1)

cv2.imshow('original', img)
cv2.imshow('res1', res1)
cv2.imshow('res2', res2)

cv2.waitKey(0)
cv2.destroyAllWindows()

## 9.图像运算：图像融合运算

- 将两张或两张以上图像的信息融合到一张图像
- 融合的图像有更多的信息，能够更方便人来观察或者用计算机进行处理
- 图像加法与图像融合
    - 图像加法：img = img1 + img2
    - 简单图像融合: 权重加法
        - img = img1 * idx1 + img2 * idx2 + 亮度调节量  （idx1+idx2=1）
        - 函数cv2.addWeighted(src1, alpha, src2, beta, gamma)
            - 结果=src1 * alpha + src2 * beta + gamma
            - 参数gamma不能省略
            - alpha,beta大者，在融合的图像中相应的src会更突出

In [52]:
src1 = cv2.imread('../image/add/boat.bmp')
# print(src1.shape)
src2 = cv2.imread('../image/lenacolor.png')
# print(src2.shape)

merged = cv2.addWeighted(src1, 0.3, src2, 2, 55)
cv2.imshow('merged', merged)
cv2.waitKey(0)
cv2.destroyAllWindows()

## 10.图像类型转换

- 将图像由一种类型转换成另一种类型
    - 彩色和灰度图像之间转换
    - 通道顺序转换
- opencv提供了200多种不同类型之间的转换
    - cv2.COLOR_BGR2GRAY
    - cv2.COLOR_BRG2RGB
    - cv2.COLOR_GRAY2BGR
    - ......
- 彩色转换成灰度
    - cv2.cvtColor(a, cv2.COLOR_BRG2GRAY)
- bgr转换rgb
    - cv2.cvtColor(a, cv2.COLOR_BRG2RGB)
- 灰度转换成BRG

In [55]:
# 彩色图像转成灰度图像
bgr2gray = cv2.cvtColor(src2, cv2.COLOR_BGR2GRAY)
bgr2rgb = cv2.cvtColor(src2, cv2.COLOR_BGR2RGB)
cv2.imshow('lena-bgr', src2)
cv2.imshow('lena-gray', bgr2gray)
cv2.imshow('lena-rgb', bgr2rgb)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [62]:
src = cv2.imread('../image/lena256.bmp', cv2.IMREAD_UNCHANGED)
print(src.shape)
toBGR = cv2.cvtColor(src, cv2.COLOR_GRAY2BGR)
print(toBGR.shape)
cv2.imshow('lena-256', src)
cv2.imshow('lena-brg', toBGR)
cv2.waitKey(0)
cv2.destroyAllWindows()

(256, 256)
(256, 256, 3)


## 11.图像几何变换

### 11.1 图像缩放

- resize函数
- dst = cv2.resize(src, dsize [, dst[, fx[, fy[, interpolation]]]])
    - src: 原始图像，必选参数
    - dsize: 缩放尺寸(列数，行数)，必选参数
        - b = cv2.resize(a, (122,122))
    - fx, fy: 通常在第二个参数不使用的时候，通过fx和fy来指定缩放尺寸
        - fx: 在水平方向上缩放多少倍，大于1表示方法，小于1表示缩小
        - fy: 在垂直方向上缩放多少倍，大于1表示方法，小于1表示缩小 
            - 例如：b = cv2.resize(a, dsize=None, fx=0.5, fy=1.5)


In [66]:
resized = cv2.resize(src2, dsize=None, fx=0.75, fy=0.75)
cv2.imshow('resized', resized)
cv2.waitKey(0)
cv2.destroyAllWindows()

### 11.2 图像翻转

- 语法：dst = cv2.flip(src, flipCode)
    - flipcode=0，表示以x轴为对称轴的上下翻转
    - flipcode=1, 表示以y轴为对称轴的左右翻转(用其他大于0的值也可以）
    - flipcode=-1, 表示同时以x轴和y轴为对称轴翻转两次(用其他小于0的值也可以）

In [68]:
fliped1 = cv2.flip(src2, 0)
fliped2 = cv2.flip(src2, 1)
fliped3 = cv2.flip(src2, -1)
cv2.imshow('original', src2)
cv2.imshow('flip1', fliped1)
cv2.imshow('flip2', fliped2)
cv2.imshow('flip3', fliped3)
cv2.waitKey(0)
cv2.destroyAllWindows()